config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  resources :events, except: [:edit, :delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attended_events
  has_many :attendees, through: :attended_events
  scope :upcoming_events, -> { where('date >= ?', Date.today) }
  scope :previous_events, -> { where('date < ?', Date.today) }
  validates :date, :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, class_name: 'Event', foreign_key: :creator_id
  has_many :attended_events, foreign_key: 'attendee_id'
  has_many :attending_events, through: :attended_events, source: :event
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user || User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  def show
    @event = Event.find(params[:id])
    @attendees = User.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:notice] = 'Event was created successfully'
      redirect_to @event
    else
      flash.now[:alert] = 'something went wrong'
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      session[:user_id] = user.id
      flash[:notice] = "welcome #{user.username}. You have been logged in"
      redirect_to user
    else
      flash.now[:alert] = 'something went wrong'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.events
    @upcoming_events = current_user.attending_events.upcoming_events
    @previous_events = current_user.attending_events.previous_events
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "welcome #{@user.username}. You have been signed up"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All events</h1>

<h2>Past events</h2>
<% @previous_events.each do |event|%>
    <p> Event: <%= event.title%></p>
    <p> Host: <%= event.creator.username%></p>
    <p> Description: <%= event.description%></p>
    <p> Date: <%= event.date%></p><br> 
<% end %>

<h2>Upcoming events</h2>
<% @upcoming_events.each do |event|%>
    <p> Event: <%= event.title%></p>
    <p> Host: <%= event.creator.username%></p>
    <p> Description: <%= event.description%></p>
    <p> Date: <%= event.date%></p><br> 
<% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_with(model: @event, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholer: 'Title of Event' %><br><br>
    <%= f.label :description %>
    <%= f.text_area :description, placeholer: 'Description of Event' %><br><br>
     <%= f.label :date %>
    <%= f.date_field :date, placeholer: 'Date of Event' %><br><br>
    <%= f.submit 'Create Event', id:'create' %>
<% end %>

app/views/events/show.html.erb
<h1>Event: <%= @event.title%></h1>

<p> Description: <%= @event.description%></p>
<p> Date: <%= @event.date%></p><br>

<ul> Attendees: <% @attendees.each do |attendee|%> </ul>
<li> <%= attendee.username%> </li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    
      <% if current_user %>
      <div><p> current user: <%=  current_user.username if current_user%></p></div>
    <nav>
      <%= link_to 'signout', logout_path, method: :delete %>
      <%= link_to 'create event', new_event_path%>
      <% else %>
      <%= link_to 'signin', login_path%>
      <%= link_to 'signup', signup_path%>
      <% end %>
      <%= link_to 'events', events_path%>

    </nav>
  </header>
   <% flash.each do |name, msg| %>
        <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome home</h1>

app/views/users/new.html.erb
<h1>sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, placeholer: 'username', id:"username"%><br><br>
    <%= f.submit 'sign up' %>
<% end %>

app/views/users/show.html.erb
<h1>user: <%= @user.username %></h1>
<h2>Events</h2>
<% @created_events.each do |event|%>
    <p> Event: <%= event.title%></p>
    <p> Description: <%= event.description%></p>
    <p> Date: <%= event.date%></p><br> 
<% end %>

<h2>Previous events</h2>
<% @previous_events.each do |event|%>
    <p> Event: <%= event.title%></p>
    <p> Description: <%= event.description%></p>
    <p> Date: <%= event.date%></p><br> 
<% end %>


<h2>Upcoming events</h2>
<% @upcoming_events.each do |event|%>
    <p> Event: <%= event.title%></p>
    <p> Description: <%= event.description%></p>
    <p> Date: <%= event.date%></p><br> 
<% end %>